# Generated by Django 5.1.7 on 2025-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
    ]
